In [1]:
from typing import Union
from typing import Tuple
from typing import List
from typing import Dict
import numpy as np

In [3]:
def split(t: np.ndarray)-> Tuple[np.ndarray, int, np.ndarray]:
    menores = np.array([elemento for elemento in t if elemento < t[0]])
    mayores = np.array([elemento for elemento in t if elemento > t[0]])
    return (menores, t[0], mayores)

def qsel(t: np.ndarray, k: int)-> Union[int, None]:
    if len(t) == 1 and k == 0:
        return t[0]
    if len(t) == 0:
        return None
    
    t_l, mid, t_r = split(t)
    m = len(t_l)
    if k == m:
        return mid
    elif k < m:
        return qsel(t_l, k)
    else:
        return qsel(t_r, k-m-1)
    

a = np.array([5, 3, 2, 1, 7, 6, 9, -1, 12, 11, -4, -10, 4])

print("a:", a)
print("qsel rec: ", qsel(a, 4))

def qsel_nr(t: np.ndarray, k: int)-> Union[int, None]:
    
    if len(t) == 1 and k == 0:
        return t[0]
    if len(t) == 0:
        return None
    

    m = len(t)
    t_aux = t

    while m >= 1:
        t_l, mid, t_r = split(t_aux)
        m = len(t_l)
        
        if k == m:
            return mid
        elif k < m:
            t_aux = t_l
        else:
            t_aux = t_r
            k = k-m-1
        
        

print("qsel ite: ", qsel_nr(a, 4))

def split_pivot(t: np.ndarray, mid: int)-> Tuple[np.ndarray, int, np.ndarray]:
    menores = np.array([elemento for elemento in t if elemento < mid])
    mayores = np.array([elemento for elemento in t if elemento > mid])
    return (menores, mid, mayores)

def pivot5(t: np.ndarray)-> int:
    t_aux = [t[x:x+5] for x in range(0, len(t), 5)]
    print(t_aux)
    medians = [sorted(x)[len(x)//2] for x in t_aux]
    print(medians)
    mid = sorted(medians)[len(medians)//2]
    return mid

def qsel5_nr(t: np.ndarray, k: int)-> Union[int, None]:

    mid = pivot5(t)
    t_aux = t
    m = len(t)
    
    while m >= 1:
        t_l, mid, t_r = split_pivot(t_aux, mid)
        print(t_l, mid, t_r)
        m = len(t_l)
        
        if k == mid:
            return mid
        elif k < mid:
            t_aux = t_l
        else:
            t_aux = t_r
            k = k-mid+1


    

print("qsel5 ite: ", qsel5_nr(a, 4))
#sorted(a)[len(a)//2]

a: [  5   3   2   1   7   6   9  -1  12  11  -4 -10   4]
qsel rec:  2
qsel ite:  2
[array([5, 3, 2, 1, 7]), array([ 6,  9, -1, 12, 11]), array([ -4, -10,   4])]
[3, 9, -4]
[  2   1  -1  -4 -10] 3 [ 5  7  6  9 12 11  4]
[] 3 [ 5  7  6  9 12 11  4]
qsel5 ite:  None


In [25]:
def knapsack_fract_greedy(l_weights: List[int], l_values: List[int], bound: int)-> Dict:

    rel_vals = [(i, l_values[i]/l_weights[i]) for i in range(len(l_values))]

    rel_vals = sorted(rel_vals,key=lambda x: x[1], reverse=True)
    elementos_mochila = {elemento: 0 for elemento in range(len(l_values))}

    ctr = 0
    while bound > 0 and len(l_values) >= ctr:
        idx, _ = rel_vals[ctr]

        if l_weights[idx] <= bound:
            bound -= l_weights[idx]
            elementos_mochila[idx] = 1
        else:
            add = bound / l_weights[idx]
            bound -= add * l_weights[idx]
            elementos_mochila[idx] = add
        ctr += 1
    
    return elementos_mochila
    

w = [1, 2, 3, 4]
v = [40, 20, 100, 60]

knapsack_fract_greedy(w, v, 5)

def knapsack_01_pd(l_weights: List[int], l_values: List[int], bound: int)-> int:
    tabla = np.zeros((len(l_weights)+1, bound+1))

    print(tabla)

knapsack_01_pd(w,v, 5)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
